name: qth_helper
description: GPS navigation helper — heading, coordinates, city finder, MOB.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^12.0.0
  flutter_compass: ^0.8.0
  wakelock_plus: ^1.2.8

flutter:
  uses-material-design: true
  assets:
    - assets/cities.tsv
